apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: polaris, namespace: argocd, annotations: {argocd.argoproj.io/sync-wave: "2"}}
spec:
  project: default
  sources:
  - repoURL: https://downloads.apache.org/polaris/helm-chart
    chart: polaris
    targetRevision: 1.7.0
    helm:
      valueFiles: [$values/platform/values/polaris.yaml]
  - repoURL: https://github.com/suhanduman/lakehouse.git
    targetRevision: v2
    ref: values
  destination: {server: https://kubernetes.default.svc, namespace: lakehouse}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
