apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: jupyterhub, namespace: argocd, annotations: {argocd.argoproj.io/sync-wave: "2"}}
spec:
  project: default
  sources:
  - repoURL: https://hub.jupyter.org/helm-chart/
    chart: jupyterhub
    targetRevision: 4.4.2
    helm:
      valueFiles: [$values/platform/values/jupyterhub.yaml]
  - repoURL: https://github.com/suhanduman/lakehouse.git
    targetRevision: main
    ref: values
  destination: {server: https://kubernetes.default.svc, namespace: lakehouse}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
