apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../apps/00-strimzi.yaml
- ../../apps/00-cnpg.yaml
- ../../apps/00-keycloak-operator.yaml
- ../../apps/10-glue.yaml
- ../../apps/20-polaris.yaml
patches:
- target: {kind: Application, name: glue}
  patch: |-
    - op: replace
      path: /spec/source/helm/valueFiles
      value: [../platform/values/glue-dev.yaml]
- target: {kind: Application, name: polaris}
  patch: |-
    - op: replace
      path: /spec/sources/0/helm/valueFiles
      value: [$values/platform/values/polaris-dev.yaml]
