{{- if and .Values.ingress.enabled (ne (include "glue.isOpenShift" .) "true") }}   {{/* openshift'te Route kullanılır */}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {name: keycloak, namespace: {{ include "glue.ns" . }}}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.keycloak.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: {service: {name: keycloak-service, port: {number: 8080}}}
{{- end }}
