{{- if and (eq (include "glue.isOpenShift" .) "true") .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata: {name: keycloak, namespace: {{ include "glue.ns" . }}}
spec:
  host: {{ include "glue.host" .Values.keycloak.hostname }}
  to: {kind: Service, name: keycloak-service}
  port: {targetPort: http}
  tls: {termination: edge}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata: {name: polaris, namespace: {{ include "glue.ns" . }}}
spec:
  to: {kind: Service, name: polaris}
  port: {targetPort: 8181}
  tls: {termination: edge}
{{- end }}
